### ISSUE TITLE
cannot load such file -- aws/s3

### ISSUE THREAD

**Issue by retorquere** [clarete/s3sync#34]
I just installed the gem, but an `s3sync help sync` yields:

    /home/emile/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- aws/s3 (LoadError)
        from /home/emile/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /home/emile/.rvm/gems/ruby-2.2.1/gems/s3sync-2.0.2/lib/s3sync/cli.rb:28:in `<top (required)>'
        from /home/emile/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/emile/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/emile/.rvm/gems/ruby-2.2.1/gems/s3sync-2.0.2/bin/s3sync:31:in `<top (required)>'
        from /home/emile/.rvm/gems/ruby-2.2.1/bin/s3sync:23:in `load'
        from /home/emile/.rvm/gems/ruby-2.2.1/bin/s3sync:23:in `<main>'
        from /home/emile/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/emile/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by peejaybee** [comment]
I believe that it is broken by the new changes to the AWS SDK gem.  I may try to get it working and submit a pull request for AWS SDK V2.

**Comment by vyorkin** [comment]
I thought dependencies in gemspec should be locked at least to major version
